### ISSUE TITLE
Update or Delete events/belief

### ISSUE THREAD

**Issue by lbenedetto** [jackokaiser/bayesian_beliefs#1]
It would be useful to be able to update or at the very least delete an event or belief

**Comment by jackokaiser** [comment]
Hi Lars,

You're absolutely right - it wasn't implemented as I wasn't sure anyone would actually use the app - but since you opened this ticket I'll happily add this feature.

**Comment by jackokaiser** [comment]
Hi Lars,

I have implemented the deletion feature in #3 - you can try it live at http://jacqueskaiser.com/bayesian_beliefs/#/
